[package]
name = "test_project"
version = "0.1.0"
authors = ["guy"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rocket_contrib = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
crossbeam = "*"
uuid = { version = "0.4", features = ["v4"] }
